/** @typedef {{ id: string, icon: string, label: string, color: string, bg: string }} AuditCategory */
/** @typedef {{
 *   id: string,
 *   persona: "tester" | "dev",
 *   group: string,
 *   name: string,
 *   shortName: string,
 *   icon: string,
 *   tagline: string,
 *   accent: string,
 *   categories: AuditCategory[],
 *   filePattern: RegExp,
 *   fileAccept: string,
 *   dropHint: string,
 *   defaultProjectName: string,
 *   checklistStorageKey: string,
 *   practicesTitle: string,
 *   practicesDoc: string,
 * }} AuditStack */

/** @type {Record<string, AuditStack>} */
export const AUDIT_STACKS = {
  // ══ TESTERS · UI automation (Playwright) ══
  playwright: {
    id: "playwright",
    persona: "tester",
    group: "UI automation",
    name: "Playwright (TS / JS)",
    shortName: "PW TS/JS",
    icon: "🎭",
    tagline: "Browser tests, locators, CI & flakiness",
    accent: "#14b8a6",
    defaultProjectName: "My Playwright Project",
    checklistStorageKey: "cqs-playwright-practices",
    practicesTitle: "Playwright E2E best practices",
    practicesDoc: "docs/PLAYWRIGHT_BEST_PRACTICES.md",
    filePattern: /\.(spec|test)\.(ts|js|tsx|jsx)$/i,
    fileAccept: ".ts,.js,.tsx,.jsx",
    dropHint: ".spec.ts / .spec.js / .test.ts / .test.js",
    loadFilesLabel: "Load test files",
    loadFolderLabel: "Load test folder",
    categories: [
      { id: "selectors", icon: "🎯", label: "Selectors", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "structure", icon: "🏗️", label: "Structure & POM", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "mobile", icon: "📱", label: "Mobile & Cross-env", color: "#db2777", bg: "#fdf2f8" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "accessibility", icon: "♿", label: "Accessibility", color: "#0284c7", bg: "#f0f9ff" },
      { id: "coding_standards", icon: "📐", label: "Coding Standards", color: "#374151", bg: "#f9fafb" },
      { id: "ci_config", icon: "⚙️", label: "CI / Config", color: "#16a34a", bg: "#f0fdf4" },
    ],
  },
  playwright_java: {
    id: "playwright_java",
    persona: "tester",
    group: "UI automation",
    name: "Playwright (Java)",
    shortName: "PW Java",
    icon: "♨️",
    tagline: "Playwright for Java — locators, waits, web-first assertions",
    accent: "#0d9488",
    defaultProjectName: "My Playwright Java Suite",
    checklistStorageKey: "cqs-playwright-java-practices",
    practicesTitle: "Playwright for Java best practices",
    practicesDoc: "docs/PLAYWRIGHT_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java Playwright tests (com.microsoft.playwright)",
    loadFilesLabel: "Load Java test files",
    loadFolderLabel: "Load Java test folder",
    categories: [
      { id: "selectors", icon: "🎯", label: "Locators", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "structure", icon: "🏗️", label: "Structure & Hooks", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "resource_mgmt", icon: "🧹", label: "Resource Mgmt", color: "#0284c7", bg: "#f0f9ff" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
      { id: "ci_config", icon: "⚙️", label: "CI / Config", color: "#16a34a", bg: "#f0fdf4" },
    ],
  },
  playwright_python: {
    id: "playwright_python",
    persona: "tester",
    group: "UI automation",
    name: "Playwright (Python)",
    shortName: "PW Python",
    icon: "🐍",
    tagline: "Playwright for Python — locators, expect(), fixtures",
    accent: "#0d9488",
    defaultProjectName: "My Playwright Python Suite",
    checklistStorageKey: "cqs-playwright-python-practices",
    practicesTitle: "Playwright for Python best practices",
    practicesDoc: "docs/PLAYWRIGHT_BEST_PRACTICES.md",
    filePattern: /\.(py)$/i,
    fileAccept: ".py",
    dropHint: ".py Playwright tests (playwright.sync_api / async_api)",
    loadFilesLabel: "Load Python test files",
    loadFolderLabel: "Load Python test folder",
    categories: [
      { id: "selectors", icon: "🎯", label: "Locators", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "structure", icon: "🏗️", label: "Structure & Fixtures", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
      { id: "ci_config", icon: "⚙️", label: "CI / Config", color: "#16a34a", bg: "#f0fdf4" },
    ],
  },

  // ── Selenium ──
  selenium_java: {
    id: "selenium_java",
    persona: "tester",
    group: "UI automation",
    name: "Selenium (Java)",
    shortName: "Selenium Java",
    icon: "🧭",
    tagline: "Java WebDriver — locators, waits, Page Objects & TestNG/JUnit",
    accent: "#dc2626",
    defaultProjectName: "My Selenium Java Suite",
    checklistStorageKey: "cqs-selenium-java-practices",
    practicesTitle: "Selenium Java best practices",
    practicesDoc: "docs/SELENIUM_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java Selenium test classes (WebDriver / ChromeDriver)",
    loadFilesLabel: "Load Java test files",
    loadFolderLabel: "Load Java test folder",
    categories: [
      { id: "locators",          icon: "🔍", label: "Locators",         color: "#14b8a6", bg: "#f0fdfa" },
      { id: "waits",             icon: "⏳", label: "Waits",             color: "#0891b2", bg: "#ecfeff" },
      { id: "assertions",        icon: "✅", label: "Assertions",        color: "#059669", bg: "#ecfdf5" },
      { id: "page_objects",      icon: "🏗️", label: "Page Objects",      color: "#7c3aed", bg: "#f5f3ff" },
      { id: "browser_mgmt",      icon: "🌐", label: "Browser Mgmt",      color: "#0284c7", bg: "#f0f9ff" },
      { id: "reliability",       icon: "🔄", label: "Reliability",       color: "#db2777", bg: "#fdf2f8" },
      { id: "security",          icon: "🔒", label: "Security",          color: "#dc2626", bg: "#fef2f2" },
      { id: "coding_standards",  icon: "📐", label: "Coding Standards",  color: "#374151", bg: "#f9fafb" },
    ],
  },
  selenium_csharp: {
    id: "selenium_csharp",
    persona: "tester",
    group: "UI automation",
    name: "Selenium (C#)",
    shortName: "Selenium C#",
    icon: "💠",
    tagline: "C# WebDriver — locators, waits, Page Objects & NUnit/xUnit",
    accent: "#7c3aed",
    defaultProjectName: "My Selenium C# Suite",
    checklistStorageKey: "cqs-selenium-csharp-practices",
    practicesTitle: "Selenium C# best practices",
    practicesDoc: "docs/SELENIUM_BEST_PRACTICES.md",
    filePattern: /\.(cs)$/i,
    fileAccept: ".cs",
    dropHint: ".cs Selenium test classes (IWebDriver / ChromeDriver)",
    loadFilesLabel: "Load C# test files",
    loadFolderLabel: "Load C# test folder",
    categories: [
      { id: "locators",          icon: "🔍", label: "Locators",         color: "#14b8a6", bg: "#f0fdfa" },
      { id: "waits",             icon: "⏳", label: "Waits",             color: "#0891b2", bg: "#ecfeff" },
      { id: "assertions",        icon: "✅", label: "Assertions",        color: "#059669", bg: "#ecfdf5" },
      { id: "page_objects",      icon: "🏗️", label: "Page Objects",      color: "#7c3aed", bg: "#f5f3ff" },
      { id: "browser_mgmt",      icon: "🌐", label: "Browser Mgmt",      color: "#0284c7", bg: "#f0f9ff" },
      { id: "reliability",       icon: "🔄", label: "Reliability",       color: "#db2777", bg: "#fdf2f8" },
      { id: "security",          icon: "🔒", label: "Security",          color: "#dc2626", bg: "#fef2f2" },
      { id: "coding_standards",  icon: "📐", label: "Coding Standards",  color: "#374151", bg: "#f9fafb" },
    ],
  },

  // ── Cypress ──
  cypress: {
    id: "cypress",
    persona: "tester",
    group: "UI automation",
    name: "Cypress (TS / JS)",
    shortName: "Cypress",
    icon: "🌲",
    tagline: "Cypress E2E — commands, assertions, network & flakiness",
    accent: "#22c55e",
    defaultProjectName: "My Cypress Suite",
    checklistStorageKey: "cqs-cypress-practices",
    practicesTitle: "Cypress best practices",
    practicesDoc: "docs/CYPRESS_BEST_PRACTICES.md",
    filePattern: /\.(cy|spec)\.(ts|js|tsx|jsx)$/i,
    fileAccept: ".ts,.js,.tsx,.jsx",
    dropHint: ".cy.ts / .cy.js / .spec.ts / .spec.js",
    loadFilesLabel: "Load Cypress test files",
    loadFolderLabel: "Load Cypress test folder",
    categories: [
      { id: "selectors",        icon: "🎯", label: "Selectors",        color: "#14b8a6", bg: "#f0fdfa" },
      { id: "commands",         icon: "⚡", label: "Commands & Flow",   color: "#22c55e", bg: "#f0fdf4" },
      { id: "assertions",       icon: "✅", label: "Assertions",        color: "#059669", bg: "#ecfdf5" },
      { id: "network",          icon: "🌐", label: "Network & Stubs",   color: "#0891b2", bg: "#ecfeff" },
      { id: "reliability",      icon: "🔄", label: "Reliability",       color: "#db2777", bg: "#fdf2f8" },
      { id: "security",         icon: "🔒", label: "Security",          color: "#dc2626", bg: "#fef2f2" },
      { id: "performance",      icon: "⚡", label: "Performance",       color: "#d97706", bg: "#fffbeb" },
      { id: "coding_standards", icon: "📐", label: "Coding Standards",  color: "#374151", bg: "#f9fafb" },
    ],
  },

  // ── Appium ──
  appium_java: {
    id: "appium_java",
    persona: "tester",
    group: "Mobile automation",
    name: "Appium (Java)",
    shortName: "Appium Java",
    icon: "📲",
    tagline: "Mobile WebDriver — iOS/Android, gestures & device management",
    accent: "#8b5cf6",
    defaultProjectName: "My Appium Java Suite",
    checklistStorageKey: "cqs-appium-java-practices",
    practicesTitle: "Appium Java best practices",
    practicesDoc: "docs/APPIUM_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java Appium test classes (AppiumDriver / IOSDriver / AndroidDriver)",
    loadFilesLabel: "Load Java test files",
    loadFolderLabel: "Load Java test folder",
    categories: [
      { id: "locators",         icon: "🔍", label: "Locators",          color: "#14b8a6", bg: "#f0fdfa" },
      { id: "waits",            icon: "⏳", label: "Waits",              color: "#0891b2", bg: "#ecfeff" },
      { id: "assertions",       icon: "✅", label: "Assertions",         color: "#059669", bg: "#ecfdf5" },
      { id: "gestures",         icon: "👆", label: "Gestures & Actions", color: "#8b5cf6", bg: "#f5f3ff" },
      { id: "driver_mgmt",      icon: "📱", label: "Driver Mgmt",        color: "#0284c7", bg: "#f0f9ff" },
      { id: "reliability",      icon: "🔄", label: "Reliability",        color: "#db2777", bg: "#fdf2f8" },
      { id: "security",         icon: "🔒", label: "Security",           color: "#dc2626", bg: "#fef2f2" },
      { id: "coding_standards", icon: "📐", label: "Coding Standards",   color: "#374151", bg: "#f9fafb" },
    ],
  },

  // ── TOSCA ──
  tosca_xml: {
    id: "tosca_xml",
    persona: "tester",
    group: "Model-based",
    name: "TOSCA (XML export)",
    shortName: "TOSCA XML",
    icon: "🧱",
    tagline: "Tricentis TOSCA — test structure, data, modules & traceability",
    accent: "#6366f1",
    defaultProjectName: "My TOSCA Export",
    checklistStorageKey: "cqs-tosca-practices",
    practicesTitle: "TOSCA best practices",
    practicesDoc: "docs/TOSCA_BEST_PRACTICES.md",
    filePattern: /\.(xml)$/i,
    fileAccept: ".xml",
    dropHint: "TOSCA XML exports (.xml — TestCase, Module, TestSheet)",
    loadFilesLabel: "Load TOSCA XML files",
    loadFolderLabel: "Load TOSCA export folder",
    categories: [
      { id: "structure",    icon: "🏗️", label: "Structure",       color: "#6366f1", bg: "#eef2ff" },
      { id: "test_data",    icon: "📊", label: "Test Data",        color: "#0891b2", bg: "#ecfeff" },
      { id: "modules",      icon: "🧩", label: "Modules & Reuse",  color: "#7c3aed", bg: "#f5f3ff" },
      { id: "descriptions", icon: "📝", label: "Documentation",    color: "#059669", bg: "#ecfdf5" },
      { id: "reliability",  icon: "🔄", label: "Reliability",      color: "#db2777", bg: "#fdf2f8" },
      { id: "maintenance",  icon: "🔧", label: "Maintenance",      color: "#d97706", bg: "#fffbeb" },
      { id: "config",       icon: "⚙️", label: "Execution Config", color: "#16a34a", bg: "#f0fdf4" },
      { id: "security",     icon: "🔒", label: "Security",         color: "#dc2626", bg: "#fef2f2" },
    ],
  },

  // ══ TESTERS · API testing ══
  restassured: {
    id: "restassured",
    persona: "tester",
    group: "API testing",
    name: "REST Assured (Java)",
    shortName: "REST Assured",
    icon: "🛡️",
    tagline: "Java REST API tests — status, schema & body assertions",
    accent: "#0d9488",
    defaultProjectName: "My REST Assured Suite",
    checklistStorageKey: "cqs-restassured-practices",
    practicesTitle: "REST Assured best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java REST Assured tests (given / when / then)",
    loadFilesLabel: "Load API test files",
    loadFolderLabel: "Load API test folder",
    categories: [
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "structure", icon: "🏗️", label: "Structure & Reuse", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "ci_config", icon: "⚙️", label: "Config / Env", color: "#16a34a", bg: "#f0fdf4" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  karate: {
    id: "karate",
    persona: "tester",
    group: "API testing",
    name: "Karate (API DSL)",
    shortName: "Karate",
    icon: "🥋",
    tagline: "Gherkin API tests — Given url / When method / Then status",
    accent: "#0d9488",
    defaultProjectName: "My Karate Suite",
    checklistStorageKey: "cqs-karate-practices",
    practicesTitle: "Karate API testing best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(feature)$/i,
    fileAccept: ".feature",
    dropHint: ".feature Karate scenarios",
    loadFilesLabel: "Load feature files",
    loadFolderLabel: "Load features folder",
    categories: [
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "structure", icon: "🏗️", label: "Structure & Reuse", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "ci_config", icon: "⚙️", label: "Config / Env", color: "#16a34a", bg: "#f0fdf4" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  pytest_api: {
    id: "pytest_api",
    persona: "tester",
    group: "API testing",
    name: "Python API (pytest)",
    shortName: "Pytest API",
    icon: "🧪",
    tagline: "pytest + requests/httpx — status, schema, fixtures",
    accent: "#0d9488",
    defaultProjectName: "My Pytest API Suite",
    checklistStorageKey: "cqs-pytest-api-practices",
    practicesTitle: "Python API testing best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(py)$/i,
    fileAccept: ".py",
    dropHint: ".py API tests (pytest + requests / httpx)",
    loadFilesLabel: "Load API test files",
    loadFolderLabel: "Load API test folder",
    categories: [
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "structure", icon: "🏗️", label: "Structure & Fixtures", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "validation", icon: "🔎", label: "Validation", color: "#16a34a", bg: "#f0fdf4" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  postman: {
    id: "postman",
    persona: "tester",
    group: "API testing",
    name: "Postman / Newman",
    shortName: "Postman",
    icon: "📮",
    tagline: "Collection tests — pm.test / pm.expect, env vars",
    accent: "#0d9488",
    defaultProjectName: "My Postman Collection",
    checklistStorageKey: "cqs-postman-practices",
    practicesTitle: "Postman / Newman best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(json)$/i,
    fileAccept: ".json",
    dropHint: "Postman collection .json (v2.1)",
    loadFilesLabel: "Load collection",
    loadFolderLabel: "Load collections folder",
    categories: [
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "ci_config", icon: "⚙️", label: "Config / Env", color: "#16a34a", bg: "#f0fdf4" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },

  // ══ DEVS · Java ══
  java_api: {
    id: "java_api",
    persona: "dev",
    group: "Java",
    name: "Java API / Core",
    shortName: "Java API",
    icon: "☕",
    tagline: "REST services, JDBC, security & JVM patterns",
    accent: "#ea580c",
    defaultProjectName: "My Java API Project",
    checklistStorageKey: "cqs-java-practices",
    practicesTitle: "Java API / core best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java sources (controllers, services, repositories)",
    loadFilesLabel: "Load Java files",
    loadFolderLabel: "Load Java project folder",
    categories: [
      { id: "api_design", icon: "🌐", label: "API Design", color: "#2563eb", bg: "#eff6ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "data_access", icon: "🗄️", label: "Data Access", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#0891b2", bg: "#ecfeff" },
      { id: "concurrency", icon: "🔀", label: "Concurrency", color: "#db2777", bg: "#fdf2f8" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "testing", icon: "🧪", label: "Testing", color: "#059669", bg: "#ecfdf5" },
      { id: "observability", icon: "📊", label: "Observability", color: "#0284c7", bg: "#f0f9ff" },
      { id: "maintainability", icon: "📦", label: "Maintainability", color: "#374151", bg: "#f9fafb" },
      { id: "java_standards", icon: "📐", label: "Java Standards", color: "#65a30d", bg: "#f7fee7" },
    ],
  },
  java_frontend: {
    id: "java_frontend",
    persona: "dev",
    group: "Java",
    name: "Java · Core / General",
    shortName: "Java Core",
    icon: "🧰",
    tagline: "General Java — correctness, errors, standards",
    accent: "#0d9488",
    defaultProjectName: "My Java Modules",
    checklistStorageKey: "cqs-java-core-practices",
    practicesTitle: "Java core / general best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java classes (non-API: domain, util, core)",
    loadFilesLabel: "Load Java files",
    loadFolderLabel: "Load Java folder",
    categories: [
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#0891b2", bg: "#ecfeff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "maintainability", icon: "📦", label: "Maintainability", color: "#374151", bg: "#f9fafb" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#65a30d", bg: "#f7fee7" },
    ],
  },

  // ══ DEVS · TypeScript / JavaScript ══
  typescript: {
    id: "typescript",
    persona: "dev",
    group: "TypeScript / JavaScript",
    name: "TypeScript Core / API",
    shortName: "TS API",
    icon: "🔷",
    tagline: "Types, async HTTP, validation & module design",
    accent: "#2563eb",
    defaultProjectName: "My TypeScript Project",
    checklistStorageKey: "cqs-typescript-practices",
    practicesTitle: "TypeScript core / API best practices",
    practicesDoc: "docs/TYPESCRIPT_BEST_PRACTICES.md",
    filePattern: /\.(ts|tsx)$/i,
    fileAccept: ".ts,.tsx",
    dropHint: ".ts / .tsx (services, clients, API handlers)",
    loadFilesLabel: "Load TypeScript files",
    loadFolderLabel: "Load TS project folder",
    categories: [
      { id: "type_safety", icon: "🔷", label: "Type Safety", color: "#2563eb", bg: "#eff6ff" },
      { id: "async_io", icon: "⏳", label: "Async & I/O", color: "#0891b2", bg: "#ecfeff" },
      { id: "http_clients", icon: "🌐", label: "HTTP Clients", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "validation", icon: "✅", label: "Validation", color: "#059669", bg: "#ecfdf5" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "structure", icon: "🏗️", label: "Structure", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#d97706", bg: "#fffbeb" },
      { id: "testing", icon: "🧪", label: "Testing", color: "#16a34a", bg: "#f0fdf4" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#ca8a04", bg: "#fefce8" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  ts_frontend: {
    id: "ts_frontend",
    persona: "dev",
    group: "TypeScript / JavaScript",
    name: "TypeScript · Frontend (React)",
    shortName: "TS Frontend",
    icon: "⚛️",
    tagline: "React/DOM — XSS, hooks, keys, accessibility",
    accent: "#0d9488",
    defaultProjectName: "My Frontend App",
    checklistStorageKey: "cqs-ts-frontend-practices",
    practicesTitle: "TypeScript frontend best practices",
    practicesDoc: "docs/TYPESCRIPT_BEST_PRACTICES.md",
    filePattern: /\.(tsx|jsx|ts)$/i,
    fileAccept: ".tsx,.jsx,.ts",
    dropHint: ".tsx / .jsx React components",
    loadFilesLabel: "Load component files",
    loadFolderLabel: "Load frontend folder",
    categories: [
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "hooks", icon: "🪝", label: "Hooks", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "accessibility", icon: "♿", label: "Accessibility", color: "#0284c7", bg: "#f0f9ff" },
      { id: "type_safety", icon: "🔷", label: "Type Safety", color: "#2563eb", bg: "#eff6ff" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },

  // ══ DEVS · Python ══
  python_api: {
    id: "python_api",
    persona: "dev",
    group: "Python",
    name: "Python · API / Core",
    shortName: "Python API",
    icon: "🗄️",
    tagline: "FastAPI / Flask / Django — SQL, secrets, validation",
    accent: "#0d9488",
    defaultProjectName: "My Python Service",
    checklistStorageKey: "cqs-python-api-practices",
    practicesTitle: "Python API / core best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(py)$/i,
    fileAccept: ".py",
    dropHint: ".py services, routers, and modules",
    loadFilesLabel: "Load Python files",
    loadFolderLabel: "Load Python project folder",
    categories: [
      { id: "api_design", icon: "🌐", label: "API Design", color: "#2563eb", bg: "#eff6ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "data_access", icon: "🗄️", label: "Data Access", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#0891b2", bg: "#ecfeff" },
      { id: "validation", icon: "✅", label: "Validation", color: "#059669", bg: "#ecfdf5" },
      { id: "async_io", icon: "⏳", label: "Async & I/O", color: "#db2777", bg: "#fdf2f8" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  python_frontend: {
    id: "python_frontend",
    persona: "dev",
    group: "Python",
    name: "Python · Frontend (Templates)",
    shortName: "Py Templates",
    icon: "🧩",
    tagline: "Django / Jinja templates — escaping, CSRF, a11y",
    accent: "#0d9488",
    defaultProjectName: "My Template Set",
    checklistStorageKey: "cqs-python-frontend-practices",
    practicesTitle: "Python template best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(html|jinja|jinja2|j2)$/i,
    fileAccept: ".html,.jinja,.j2",
    dropHint: "Django / Jinja templates (.html, .j2)",
    loadFilesLabel: "Load templates",
    loadFolderLabel: "Load templates folder",
    categories: [
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "accessibility", icon: "♿", label: "Accessibility", color: "#0284c7", bg: "#f0f9ff" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
};

export const DEFAULT_STACK_ID = "playwright";

export const STACK_LIST = Object.values(AUDIT_STACKS);

/** Personas position the tool by audience: test code vs application code. */
export const PERSONAS = [
  { id: "tester", label: "Testers", blurb: "Validate your test suites", reportNoun: "Test Suite Quality" },
  { id: "dev", label: "Devs", blurb: "Validate application code", reportNoun: "Code Quality" },
];

export function getPersona(personaId) {
  return PERSONAS.find((p) => p.id === personaId) ?? PERSONAS[0];
}

export function getPersonaForStack(stackId) {
  return AUDIT_STACKS[stackId]?.persona ?? "tester";
}

export function defaultStackForPersona(personaId) {
  const s = STACK_LIST.find((x) => x.persona === personaId);
  return s ? s.id : DEFAULT_STACK_ID;
}

/** Stacks for a persona, grouped by `group` label (preserving declaration order). */
export function getStacksByPersona(personaId) {
  const groups = [];
  const byLabel = new Map();
  for (const s of STACK_LIST) {
    if (s.persona !== personaId) continue;
    const label = s.group || "Other";
    if (!byLabel.has(label)) {
      const entry = { group: label, stacks: [] };
      byLabel.set(label, entry);
      groups.push(entry);
    }
    byLabel.get(label).stacks.push(s);
  }
  return groups;
}
