/** @typedef {{ id: string, icon: string, label: string, color: string, bg: string }} AuditCategory */
/** @typedef {{
 *   id: string,
 *   name: string,
 *   shortName: string,
 *   icon: string,
 *   tagline: string,
 *   accent: string,
 *   categories: AuditCategory[],
 *   filePattern: RegExp,
 *   fileAccept: string,
 *   dropHint: string,
 *   defaultProjectName: string,
 *   checklistStorageKey: string,
 * }} AuditStack */

/** @type {Record<string, AuditStack>} */
export const AUDIT_STACKS = {
  playwright: {
    id: "playwright",
    name: "Playwright (TS / JS)",
    shortName: "PW TS/JS",
    icon: "⚡",
    tagline: "Browser tests, locators, CI & flakiness",
    accent: "#14b8a6",
    defaultProjectName: "My Playwright Project",
    checklistStorageKey: "pqs-playwright-practices",
    practicesTitle: "Playwright E2E best practices",
    practicesDoc: "docs/PLAYWRIGHT_BEST_PRACTICES.md",
    filePattern: /\.(spec|test)\.(ts|js|tsx|jsx)$/i,
    fileAccept: ".ts,.js,.tsx,.jsx",
    dropHint: ".spec.ts / .spec.js / .test.ts / .test.js",
    loadFilesLabel: "Load test files",
    loadFolderLabel: "Load test folder",
    categories: [
      { id: "selectors", icon: "🎯", label: "Selectors", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "structure", icon: "🏗️", label: "Structure & POM", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "mobile", icon: "📱", label: "Mobile & Cross-env", color: "#db2777", bg: "#fdf2f8" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "accessibility", icon: "♿", label: "Accessibility", color: "#0284c7", bg: "#f0f9ff" },
      { id: "coding_standards", icon: "📐", label: "Coding Standards", color: "#374151", bg: "#f9fafb" },
      { id: "ci_config", icon: "⚙️", label: "CI / Config", color: "#16a34a", bg: "#f0fdf4" },
    ],
  },
  playwright_java: {
    id: "playwright_java",
    name: "Playwright (Java)",
    shortName: "PW Java",
    icon: "🎭",
    tagline: "Playwright for Java — locators, waits, web-first assertions",
    accent: "#0d9488",
    defaultProjectName: "My Playwright Java Suite",
    checklistStorageKey: "pqs-playwright-java-practices",
    practicesTitle: "Playwright for Java best practices",
    practicesDoc: "docs/PLAYWRIGHT_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java Playwright tests (com.microsoft.playwright)",
    loadFilesLabel: "Load Java test files",
    loadFolderLabel: "Load Java test folder",
    categories: [
      { id: "selectors", icon: "🎯", label: "Locators", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "structure", icon: "🏗️", label: "Structure & Hooks", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "resource_mgmt", icon: "🧹", label: "Resource Mgmt", color: "#0284c7", bg: "#f0f9ff" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
      { id: "ci_config", icon: "⚙️", label: "CI / Config", color: "#16a34a", bg: "#f0fdf4" },
    ],
  },
  java_api: {
    id: "java_api",
    name: "Java API / Core",
    shortName: "Java",
    icon: "☕",
    tagline: "REST services, JDBC, security & JVM patterns",
    accent: "#ea580c",
    defaultProjectName: "My Java API Project",
    checklistStorageKey: "pqs-java-practices",
    practicesTitle: "Java API / core best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java sources (controllers, services, repositories)",
    loadFilesLabel: "Load Java files",
    loadFolderLabel: "Load Java project folder",
    categories: [
      { id: "api_design", icon: "🌐", label: "API Design", color: "#2563eb", bg: "#eff6ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "data_access", icon: "🗄️", label: "Data Access", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#0891b2", bg: "#ecfeff" },
      { id: "concurrency", icon: "🔀", label: "Concurrency", color: "#db2777", bg: "#fdf2f8" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "testing", icon: "🧪", label: "Testing", color: "#059669", bg: "#ecfdf5" },
      { id: "observability", icon: "📊", label: "Observability", color: "#0284c7", bg: "#f0f9ff" },
      { id: "maintainability", icon: "📦", label: "Maintainability", color: "#374151", bg: "#f9fafb" },
      { id: "java_standards", icon: "📐", label: "Java Standards", color: "#65a30d", bg: "#f7fee7" },
    ],
  },
  typescript: {
    id: "typescript",
    name: "TypeScript Core / API",
    shortName: "TypeScript",
    icon: "🔷",
    tagline: "Types, async HTTP, validation & module design",
    accent: "#2563eb",
    defaultProjectName: "My TypeScript Project",
    checklistStorageKey: "pqs-typescript-practices",
    practicesTitle: "TypeScript core / API best practices",
    practicesDoc: "docs/TYPESCRIPT_BEST_PRACTICES.md",
    filePattern: /\.(ts|tsx)$/i,
    fileAccept: ".ts,.tsx",
    dropHint: ".ts / .tsx (services, clients, API handlers)",
    loadFilesLabel: "Load TypeScript files",
    loadFolderLabel: "Load TS project folder",
    categories: [
      { id: "type_safety", icon: "🔷", label: "Type Safety", color: "#2563eb", bg: "#eff6ff" },
      { id: "async_io", icon: "⏳", label: "Async & I/O", color: "#0891b2", bg: "#ecfeff" },
      { id: "http_clients", icon: "🌐", label: "HTTP Clients", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "validation", icon: "✅", label: "Validation", color: "#059669", bg: "#ecfdf5" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "structure", icon: "🏗️", label: "Structure", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#d97706", bg: "#fffbeb" },
      { id: "testing", icon: "🧪", label: "Testing", color: "#16a34a", bg: "#f0fdf4" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#ca8a04", bg: "#fefce8" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  playwright_python: {
    id: "playwright_python",
    name: "Playwright (Python)",
    shortName: "PW Python",
    icon: "🐍",
    tagline: "Playwright for Python — locators, expect(), fixtures",
    accent: "#0d9488",
    defaultProjectName: "My Playwright Python Suite",
    checklistStorageKey: "pqs-playwright-python-practices",
    practicesTitle: "Playwright for Python best practices",
    practicesDoc: "docs/PLAYWRIGHT_BEST_PRACTICES.md",
    filePattern: /\.(py)$/i,
    fileAccept: ".py",
    dropHint: ".py Playwright tests (playwright.sync_api / async_api)",
    loadFilesLabel: "Load Python test files",
    loadFolderLabel: "Load Python test folder",
    categories: [
      { id: "selectors", icon: "🎯", label: "Locators", color: "#14b8a6", bg: "#f0fdfa" },
      { id: "reliability", icon: "🔄", label: "Reliability", color: "#0891b2", bg: "#ecfeff" },
      { id: "assertions", icon: "✅", label: "Assertions", color: "#059669", bg: "#ecfdf5" },
      { id: "structure", icon: "🏗️", label: "Structure & Fixtures", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
      { id: "ci_config", icon: "⚙️", label: "CI / Config", color: "#16a34a", bg: "#f0fdf4" },
    ],
  },
  ts_frontend: {
    id: "ts_frontend",
    name: "TypeScript · Frontend (React)",
    shortName: "TS Frontend",
    icon: "⚛️",
    tagline: "React/DOM — XSS, hooks, keys, accessibility",
    accent: "#0d9488",
    defaultProjectName: "My Frontend App",
    checklistStorageKey: "pqs-ts-frontend-practices",
    practicesTitle: "TypeScript frontend best practices",
    practicesDoc: "docs/TYPESCRIPT_BEST_PRACTICES.md",
    filePattern: /\.(tsx|jsx|ts)$/i,
    fileAccept: ".tsx,.jsx,.ts",
    dropHint: ".tsx / .jsx React components",
    loadFilesLabel: "Load component files",
    loadFolderLabel: "Load frontend folder",
    categories: [
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "hooks", icon: "🪝", label: "Hooks", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "accessibility", icon: "♿", label: "Accessibility", color: "#0284c7", bg: "#f0f9ff" },
      { id: "type_safety", icon: "🔷", label: "Type Safety", color: "#2563eb", bg: "#eff6ff" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  python_api: {
    id: "python_api",
    name: "Python · API / Core",
    shortName: "Python API",
    icon: "🐍",
    tagline: "FastAPI / Flask / Django — SQL, secrets, validation",
    accent: "#0d9488",
    defaultProjectName: "My Python Service",
    checklistStorageKey: "pqs-python-api-practices",
    practicesTitle: "Python API / core best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(py)$/i,
    fileAccept: ".py",
    dropHint: ".py services, routers, and modules",
    loadFilesLabel: "Load Python files",
    loadFolderLabel: "Load Python project folder",
    categories: [
      { id: "api_design", icon: "🌐", label: "API Design", color: "#2563eb", bg: "#eff6ff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "data_access", icon: "🗄️", label: "Data Access", color: "#7c3aed", bg: "#f5f3ff" },
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#0891b2", bg: "#ecfeff" },
      { id: "validation", icon: "✅", label: "Validation", color: "#059669", bg: "#ecfdf5" },
      { id: "async_io", icon: "⏳", label: "Async & I/O", color: "#db2777", bg: "#fdf2f8" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  python_frontend: {
    id: "python_frontend",
    name: "Python · Frontend (Templates)",
    shortName: "Py Templates",
    icon: "🧩",
    tagline: "Django / Jinja templates — escaping, CSRF, a11y",
    accent: "#0d9488",
    defaultProjectName: "My Template Set",
    checklistStorageKey: "pqs-python-frontend-practices",
    practicesTitle: "Python template best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(html|jinja|jinja2|j2)$/i,
    fileAccept: ".html,.jinja,.j2",
    dropHint: "Django / Jinja templates (.html, .j2)",
    loadFilesLabel: "Load templates",
    loadFolderLabel: "Load templates folder",
    categories: [
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "accessibility", icon: "♿", label: "Accessibility", color: "#0284c7", bg: "#f0f9ff" },
      { id: "standards", icon: "📐", label: "Standards", color: "#374151", bg: "#f9fafb" },
    ],
  },
  java_frontend: {
    id: "java_frontend",
    name: "Java · Core / General",
    shortName: "Java Core",
    icon: "🧰",
    tagline: "General Java — correctness, errors, standards",
    accent: "#0d9488",
    defaultProjectName: "My Java Modules",
    checklistStorageKey: "pqs-java-core-practices",
    practicesTitle: "Java core / general best practices",
    practicesDoc: "docs/JAVA_API_BEST_PRACTICES.md",
    filePattern: /\.(java)$/i,
    fileAccept: ".java",
    dropHint: ".java classes (non-API: domain, util, core)",
    loadFilesLabel: "Load Java files",
    loadFolderLabel: "Load Java folder",
    categories: [
      { id: "error_handling", icon: "🛡️", label: "Error Handling", color: "#0891b2", bg: "#ecfeff" },
      { id: "security", icon: "🔒", label: "Security", color: "#dc2626", bg: "#fef2f2" },
      { id: "performance", icon: "⚡", label: "Performance", color: "#d97706", bg: "#fffbeb" },
      { id: "maintainability", icon: "📦", label: "Maintainability", color: "#374151", bg: "#f9fafb" },
      { id: "coding_standards", icon: "📐", label: "Standards", color: "#65a30d", bg: "#f7fee7" },
    ],
  },
};

export const DEFAULT_STACK_ID = "playwright";

export const STACK_LIST = Object.values(AUDIT_STACKS);
