/**
 * prBot.js — GitHub PR review bot for qcBot.
 *
 * Run as a GitHub Actions step:
 *   npx @cqs/qcbot pr-review --threshold 80
 *
 * Or manually:
 *   npx @cqs/qcbot pr-review \
 *     --token ghp_xxx \
 *     --repo owner/repo \
 *     --pr 42 \
 *     --threshold 80
 *
 * Env vars read automatically from GitHub Actions context:
 *   GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_REF (refs/pull/42/merge)
 */

import { readFile } from "fs/promises";
import { existsSync } from "fs";
import { resolve, basename } from "path";
import { program } from "commander";
import { runLocalAnalysis } from "../../src/analyzers/index.js";
import { runCrossFileAnalysis } from "../../src/analyzers/crossFileAnalyzer.js";
import { AUDIT_STACKS } from "../../src/stacks/definitions.js";

const RESET  = "\x1b[0m";
const GREEN  = "\x1b[32m";
const RED    = "\x1b[31m";
const TEAL   = "\x1b[36m";
const GRAY   = "\x1b[90m";
const BOLD   = "\x1b[1m";

// ── GitHub API helpers ────────────────────────────────────────────────────

async function ghFetch(path, token, options = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers || {}),
    },
    body: options.body ? JSON.stringify(options.body) : undefined,
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`GitHub API ${res.status}: ${txt.slice(0, 300)}`);
  }
  return res.json();
}

async function getPrFiles(owner, repo, prNumber, token) {
  // GitHub returns max 30 files per page; handle pagination
  const files = [];
  let page = 1;
  while (true) {
    const chunk = await ghFetch(
      `/repos/${owner}/${repo}/pulls/${prNumber}/files?per_page=100&page=${page}`,
      token,
    );
    files.push(...chunk);
    if (chunk.length < 100) break;
    page++;
  }
  return files;
}

async function getPrCommit(owner, repo, prNumber, token) {
  const pr = await ghFetch(`/repos/${owner}/${repo}/pulls/${prNumber}`, token);
  return pr.head.sha;
}

async function postReview(owner, repo, prNumber, token, { commitId, body, comments, event }) {
  return ghFetch(`/repos/${owner}/${repo}/pulls/${prNumber}/reviews`, token, {
    method: "POST",
    body: { commit_id: commitId, body, comments, event },
  });
}

// ── Score helpers ─────────────────────────────────────────────────────────

function gradeLabel(score) {
  if (score >= 90) return "Excellent ✅";
  if (score >= 75) return "Good ✅";
  if (score >= 60) return "Fair ⚠️";
  return "Needs work ❌";
}

function buildReviewBody({ score, passed, threshold, files, stackId }) {
  const grade = gradeLabel(score);
  const allFindings = files.flatMap((f) => (f.result?.findings || []).map((fi) => ({ ...fi, _file: f.name })));
  const critical = allFindings.filter((f) => f.severity === "critical").length;
  const warnings = allFindings.filter((f) => f.severity === "warning").length;

  const lines = [
    `## ⚡ qcBot Report — ${passed ? "PASSED ✅" : "FAILED ❌"}`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Overall score | **${score}** — ${grade} |`,
    `| Threshold | ${threshold} |`,
    `| Files analysed | ${files.length} |`,
    `| Critical findings | ${critical} |`,
    `| Warnings | ${warnings} |`,
    `| Stack | \`${stackId}\` |`,
    ``,
    passed
      ? `✅ This PR meets the quality threshold of **${threshold}**. Great work!`
      : `❌ This PR's quality score (**${score}**) is below the threshold of **${threshold}**. Please address the critical findings before merging.`,
    ``,
  ];

  if (critical > 0) {
    lines.push(`### 🔴 Critical findings to fix`);
    allFindings
      .filter((f) => f.severity === "critical")
      .slice(0, 10)
      .forEach((f) => {
        lines.push(`- **${f.title}** — \`${f._file}\`${f.line ? `:${f.line}` : ""} (\`${f.ruleId || ""}\`)`);
      });
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`*Generated by [qcbot](https://github.com/cqs/qcbot) · Stack: \`${stackId}\` · [Learn more about the rules](https://github.com/cqs/qcbot/blob/main/cli/README.md)*`);
  return lines.join("\n");
}

// ── Main command ──────────────────────────────────────────────────────────

async function runPrReview(opts) {
  // Resolve credentials — prefer explicit opts, fall back to GitHub Actions env
  const token = opts.token || process.env.GITHUB_TOKEN;
  if (!token) {
    console.error(`${RED}✗ No GitHub token. Pass --token or set GITHUB_TOKEN.${RESET}`);
    process.exit(1);
  }

  let owner, repo;
  if (opts.repo) {
    [owner, repo] = opts.repo.split("/");
  } else if (process.env.GITHUB_REPOSITORY) {
    [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
  } else {
    console.error(`${RED}✗ No repo. Pass --repo owner/repo or set GITHUB_REPOSITORY.${RESET}`);
    process.exit(1);
  }

  let prNumber = opts.pr;
  if (!prNumber && process.env.GITHUB_REF) {
    // refs/pull/42/merge
    const m = process.env.GITHUB_REF.match(/refs\/pull\/(\d+)/);
    if (m) prNumber = parseInt(m[1], 10);
  }
  if (!prNumber) {
    console.error(`${RED}✗ No PR number. Pass --pr 42 or run inside a GitHub Actions pull_request event.${RESET}`);
    process.exit(1);
  }

  const stackId = opts.stack || "playwright";
  const threshold = Number(opts.threshold) || 80;

  if (!AUDIT_STACKS[stackId]) {
    console.error(`${RED}✗ Unknown stack "${stackId}"${RESET}`);
    process.exit(1);
  }

  const stackDef = AUDIT_STACKS[stackId];
  const pattern = stackDef.filePattern;

  console.log(`\n${BOLD}⚡ qcBot PR Review${RESET}`);
  console.log(`${GRAY}   ${owner}/${repo} · PR #${prNumber} · stack: ${stackId} · threshold: ${threshold}${RESET}\n`);

  // 1. Get list of files changed in the PR
  console.log(`${TEAL}→${RESET} Fetching PR files…`);
  const prFiles = await getPrFiles(owner, repo, prNumber, token);
  const specFiles = prFiles.filter((f) => f.status !== "removed" && pattern.test(basename(f.filename)));

  if (specFiles.length === 0) {
    console.log(`${GRAY}  No ${stackDef.dropHint} files changed in this PR — skipping quality review.${RESET}\n`);
    process.exit(0);
  }

  console.log(`${TEAL}→${RESET} ${specFiles.length} test file(s) changed in this PR`);

  // 2. Read files from disk and analyse
  const cwd = process.cwd();
  const fileResults = [];
  for (const pf of specFiles) {
    const absPath = resolve(cwd, pf.filename);
    if (!existsSync(absPath)) {
      console.log(`${GRAY}  Skipping ${pf.filename} (not on disk — likely deleted)${RESET}`);
      continue;
    }
    try {
      const content = await readFile(absPath, "utf8");
      const name = pf.filename;
      const result = runLocalAnalysis(stackId, basename(name), content);
      fileResults.push({ name, content, result });
    } catch (err) {
      console.log(`${GRAY}  Skipping ${pf.filename}: ${err.message}${RESET}`);
    }
  }

  if (fileResults.length === 0) {
    console.log(`${GRAY}  No files could be read — nothing to review.${RESET}\n`);
    process.exit(0);
  }

  // 3. Cross-file pass
  if (fileResults.length >= 2) {
    const crossMap = runCrossFileAnalysis(fileResults);
    for (const fr of fileResults) {
      if (crossMap[fr.name]) {
        fr.result = { ...fr.result, findings: [...(fr.result.findings || []), ...crossMap[basename(fr.name)]] };
      }
    }
  }

  // 4. Aggregate
  const scores = fileResults.map((f) => f.result?.overallScore ?? 0);
  const avgScore = Math.round(scores.reduce((a, b) => a + b, 0) / scores.length);
  const passed = avgScore >= threshold;

  // 5. Build inline comments — one per critical/warning finding
  const MAX_INLINE = 30; // GitHub caps reviews at 30 comments
  const inlineComments = [];
  for (const fr of fileResults) {
    const findings = (fr.result?.findings || []).filter((f) => f.severity === "critical" || f.severity === "warning");
    for (const finding of findings) {
      if (inlineComments.length >= MAX_INLINE) break;
      // Only post inline if we have a line number and the file appears in the diff
      const prFile = prFiles.find((pf) => pf.filename === fr.name);
      if (!prFile || !finding.line) continue;

      const sevEmoji = finding.severity === "critical" ? "🔴" : "⚠️";
      const body = [
        `${sevEmoji} **${finding.severity.toUpperCase()}**: ${finding.title}`,
        ``,
        finding.description,
        ``,
        finding.fix ? `**Fix:** ${finding.fix.replace(/\n/g, "\n\n")}` : "",
        ``,
        finding.ruleId ? `*Rule: \`${finding.ruleId}\`*` : "",
        finding.reference && finding.reference.startsWith("http") ? `[Learn more ↗](${finding.reference})` : "",
      ].filter(Boolean).join("\n");

      inlineComments.push({
        path: fr.name,
        line: finding.line,
        side: "RIGHT",
        body,
      });
    }
  }

  // 6. Get the head commit SHA for the review
  const commitId = await getPrCommit(owner, repo, prNumber, token);

  // 7. Build review body
  const reviewBody = buildReviewBody({ score: avgScore, passed, threshold, files: fileResults, stackId });

  // 8. Post the review
  const event = passed ? "APPROVE" : (inlineComments.length > 0 ? "REQUEST_CHANGES" : "COMMENT");
  console.log(`${TEAL}→${RESET} Posting GitHub review (${event}) with ${inlineComments.length} inline comment(s)…`);

  try {
    await postReview(owner, repo, prNumber, token, {
      commitId,
      body: reviewBody,
      comments: inlineComments,
      event: opts.dryRun ? "COMMENT" : event,
    });
    console.log(`\n${GREEN}✓ Review posted${RESET}`);
    console.log(`  Score: ${avgScore}  Status: ${passed ? "PASSED ✅" : "FAILED ❌"}`);
    console.log(`  Inline comments: ${inlineComments.length}\n`);
  } catch (err) {
    console.error(`${RED}✗ Failed to post review: ${err.message}${RESET}`);
    // Don't fail the CI step just because review posting failed
    // The exit code below reflects the quality gate
  }

  process.exit(passed ? 0 : 1);
}

// ── Commander registration (called from cli.js) ───────────────────────────

export function registerPrReviewCommand(program) {
  program
    .command("pr-review")
    .description("Post a quality review on a GitHub Pull Request")
    .option("--token <token>",     "GitHub token (default: $GITHUB_TOKEN)")
    .option("--repo <owner/repo>", "Repository slug (default: $GITHUB_REPOSITORY)")
    .option("--pr <number>",       "PR number (default: auto-detected from $GITHUB_REF)", parseInt)
    .option("-s, --stack <id>",    "Stack to analyse",   "playwright")
    .option("-t, --threshold <n>", "Minimum passing score", "80")
    .option("--dry-run",           "Post as COMMENT instead of APPROVE/REQUEST_CHANGES")
    .action(runPrReview);
}
